version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/reporting-rshiny-grofwildjacht
hooks:
  BeforeInstall:
    - location: scripts/cleanup-reporting-rshiny-grofwildjacht.sh
      timeout: 300
  AfterInstall:
    - location: scripts/reporting-rshiny-grofwildjacht.sh
      timeout: 3600
permissions:
  - object: /home/ubuntu/reporting-rshiny-grofwildjacht
    owner: ubuntu
    group: ubuntu
mode: 764
