# Please do not edit this file, as it is managed by roar
{ rUtils, ... }:
final: prev:
let
  buildCranRPackage = rUtils.lib.buildCranRPackage final prev;
  buildBiocRPackage = rUtils.lib.buildBiocRPackage final prev;
  buildGitHubRPackage = rUtils.lib.buildGitHubRPackage final prev;
  buildCraneRPackage = rUtils.lib.buildCraneRPackage final prev;
in
{
  rPackages = prev.rPackages.override {
    overrides = {
      oaStyle = buildCraneRPackage {
        name = "oaStyle";
        version = "0.4.7";
        hash = "sha256-kAfCfdEvHORkHZXwj1nio8NPqi/PrCxfvcgDcGllBmk=";
        crane_url = "https://repos.openanalytics.eu";
        crane_repo = "public";
      };
      aws_ec2metadata = prev.rPackages.aws_ec2metadata.overrideAttrs (old: {
        meta = old.meta // {
          broken = false;
        };
      });
      leaflet_extras = prev.rPackages.leaflet_extras.overrideAttrs (old: {
        meta = old.meta // {
          broken = false;
        };
      });
      slickR = prev.rPackages.slickR.overrideAttrs (old: {
        meta = old.meta // {
          broken = false;
        };
      });
      INBOtheme = buildGitHubRPackage {
        name = "INBOtheme";
        version = "0.6.1"; # This version was extracted from the DESCRIPTION file
        hash = "sha256-32dzA3m80DMOxU2vYeRo6+zchiYRJyxMghIqBEP4aWM=";
        owner = "inbo";
        repo = "INBOtheme";
        commit = "44e13c757753492193992895dddea62ac1852ffa";
      };
    };
  };
}
