---
title: "Datavoorbereiding Agouti export"
author: "Lynn Pallemaerts"
date: "2023-01-03"
output: html-document
---

# Libraries

```{r}
library(camtraptor)
library(lubridate)
library(tidyverse)
```

# Unzipping

```{r}
unzip("./dashboard/input/gmu8.zip",
      exdir = "./Grofwild/Dashboard/Input/Cameravallen/filesGMU8")
GMU8 <- camtraptor::read_camtrap_dp(file = "./Grofwild/Dashboard/Input/Cameravallen/filesGMU8")
```

```{r}
# Check parsing problems:
problems(GMU8$data$deployments) # all good
problems(GMU8$data$observations) # 14 issues
# no datetime given, probably camera bug
problems(GMU8$data$media) # all good
# Nothing to worry about, ignoring it
```

# Data cleaning

```{r}
GMU8$data$deployments <- GMU8$data$deployments %>% 
  filter(locationName != "1348 2019-2021") %>%
  mutate(var = locationName) %>%
  separate(var, into = c("year_loc", "serie", "gridcell"), "_")
GMU8$data$deployments <- GMU8$data$deployments %>%
  filter(tags == "Meerdaal Oost" | tags == "Meerdaal West")

depID <- unique(GMU8$data$deployments$deploymentID)

GMU8$data$observations <- GMU8$data$observations %>%
  filter(deploymentID %in% depID)

GMU8$data$media <- GMU8$data$media %>%
  filter(deploymentID %in% depID)
```

# Definiëer kalenderjaar

```{r}
GMU8$data$deployments$calYear <- GMU8$data$deployments$year_loc
```

# Zomer/winter definiëren

```{r}
GMU8$data$deployments <- GMU8$data$deployments[order(GMU8$data$deployments$start), ] # helps to visualise if it worked
GMU8$data$deployments <- GMU8$data$deployments %>% 
  mutate(day = day(start), 
         month = month(start), 
         Season  = case_when(month == 3 & day >= 26 | month %in% 4:8 | month == 9 & day <= 3 ~ "Zomer", 
                             TRUE ~ "Winter"),
         ymOne = as.numeric(year_loc) - 1,
         mon = case_when(Season == "Zomer" ~ paste0(Season, year_loc), 
                         Season == "Winter" & month %in% 8:12 ~ paste0(Season, year_loc),
                         Season == "Winter" & month %in% 1:3 ~ paste0(Season, ymOne)))
```

# RAI per seizoen

```{r}
rai <- data.frame()
for (i in unique(GMU8$data$deployments$mon)) {
  res <- get_rai(package = GMU8,
                 species = "Sus scrofa",
                 pred = pred("mon", i))
  res <- res %>%
    mutate(MonitoringSeason = i)
  rai <- rbind(rai,
               res)
}
rai <- rai %>%
  mutate(MonitoringYear = substr(MonitoringSeason, 
                                 start = nchar(MonitoringSeason) - 3,
                                 stop = nchar(MonitoringSeason)))
rai <- rai %>%
  left_join(GMU8$data$deployments %>%
              select(deploymentID, longitude, latitude, start, end, calYear, Season),
            by = "deploymentID")
```

# Add naive occupancy

```{r}
rai <- rai %>%
  mutate(pres = case_when(rai == 0 ~ 0,
                          TRUE ~ 1))
```

# Unlink files

```{r}
unlink("./Grofwild/Dashboard/Input/Cameravallen/filesGMU8", recursive = TRUE)
```
