#Libraries
```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
Data_inschatting <- read.csv("./dashboard/input/maatschappelijke_draagkracht/Data_inschatting.csv")
```

#Test grafiek
```{r}
landbouw_inschatting <- Data_inschatting %>%
  filter(Vraag == "schade_landbouw_evolutie")


landbouw_inschatting$Antwoord <- factor(landbouw_inschatting$Antwoord , 
                                    levels = c('Erg veel toegenomen','Veel toegenomen',
                                               'Beetje toegenomen', 'Hetzelfde gebleven',
                                               'Beetje afgenomen', 'Veel afgenomen',
                                               'Erg veel afgenomen'))

plot_inschatting_landbouw <- ggplot(data = landbouw_inschatting[order(landbouw_inschatting$Score), ],
                           aes(x = percentage,
                               y = Vraag,
                               fill = Antwoord)) +
  geom_bar(stat = "identity", 
           position = "stack")

plot_inschatting_landbouw

```
