default:
  bucket: inbo-wbe-uat-data
  credentials:
    region: Sys.getenv('AWS_DEFAULT_REGION', unset = 'eu-west-1')
    id: Sys.getenv('AWS_ACCESS_KEY_ID')
    secret: Sys.getenv('AWS_SECRET_ACCESS_KEY')
  datacheck: true 

uat:
  bucket: inbo-wbe-uat-data
  datacheck: true
    
production:
  bucket: inbo-wbe-prd-data
  datacheck: false
